# Generated by Django 2.2.2 on 2020-08-01 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.SlugField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('moderators', models.ManyToManyField(related_name='moderated_subs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
