# Generated by Django 2.2.2 on 2020-08-01 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('redditors', '0001_initial'),
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmembership',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subs.Sub'),
        ),
        migrations.AddField(
            model_name='usersubmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='subs',
            field=models.ManyToManyField(related_name='members', through='redditors.UserSubMembership', to='subs.Sub'),
        ),
        migrations.AlterUniqueTogether(
            name='usersubmembership',
            unique_together={('user', 'sub')},
        ),
    ]
