# Generated by Django 2.2.2 on 2020-08-01 06:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_bleach.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loanrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', django_bleach.models.BleachField(validators=[django.core.validators.MaxLengthValidator(150, message='The title can only be 150 characters in length.')])),
                ('loanamount', models.IntegerField()),
                ('body', django_bleach.models.BleachField(blank=True)),
            ],
        ),
    ]
